export const gallery =[
    {
        id:1,
        name:'uniform',
        image:'./uniform.jpeg',
        price:12000,
        rating:5
    },
    {
        id:2,
        name:'vikoi',
        image:'vikoi.jpeg',
        price:15000,
        rating:4
    },
    {
        id:3,
        name:'men',
        image:'men.jpeg',
        price:18000,
        rating:5
    },
    {
        id:1,
        name:'women',
        image:'./women.jpg',
        price:17000,
        rating:3
    },
    {
        id:2,
        name:'bedsheet',
        image:'bedsheet.jpeg',
        price:13000,
        rating:4
    },
    {
        id:3,
        name:'curtains',
        image:'curtains.jpeg',
        price:48000,
        rating:3
    }
]